version: "3.8"

services:
  # Node.js service
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: ${POSTGRES_USER} # Use variable substitution
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT:-5432} # Default to 5432 if not set
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
