version: "3.8"

services:
  # NGINX reverse proxy service
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Expose HTTP port 80
      - "443:443" # Expose HTTPS port 443 (optional if you want to serve HTTPS)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount your custom NGINX configuration file
    depends_on:
      - node
    networks:
      - app-network

  # Node.js service
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Use variable substitution
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432} # Default to 5432 if not set
      PORT: ${PORT:-3000}
    expose:
      - "3000" # Expose port 3000 for internal use by NGINX
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
